<?php
/*
 *	minim - PHP framework
    Copyright (C) 2019  Sébastien Boulard

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; see the file COPYING. If not, write to the
    Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */
final class LangSwitcher {
	
	public static $aFlagsName = array (
							0 => 'KR',
							1 => 'BA',
							2 => 'LY',
							3 => 'HK',
							4 => 'AX',
							5 => 'BF',
							6 => 'VU',
							7 => 'BH',
							8 => 'BO',
							9 => 'EC',
							10 => 'EUROPEANUNION',
							11 => 'LK',
							12 => 'VI',
							13 => 'BT',
							14 => 'KG',
							15 => 'BS',
							16 => 'AM',
							17 => 'VN',
							18 => 'KN',
							19 => 'FO',
							20 => 'LB',
							21 => 'AD',
							22 => 'RU',
							23 => 'VG',
							24 => 'BZ',
							25 => 'KI',
							26 => 'UY',
							27 => 'WF',
							28 => 'ST',
							29 => 'MD',
							30 => 'GI',
							31 => 'NZ',
							32 => 'PM',
							33 => 'GN',
							34 => 'JO',
							35 => 'IQ',
							36 => 'MC',
							37 => 'CR',
							38 => 'MM',
							39 => 'SZ',
							40 => 'TV',
							41 => 'CU',
							42 => 'TM',
							43 => 'NO',
							44 => 'CN',
							45 => 'WS',
							46 => 'SA',
							47 => 'MQ',
							48 => 'ID',
							49 => 'MV',
							50 => 'DE',
							51 => 'TJ',
							52 => 'CI',
							53 => 'SH',
							54 => 'MX',
							55 => 'DK',
							56 => 'YE',
							57 => 'TD',
							58 => 'NF',
							59 => 'GU',
							60 => 'CG',
							61 => 'TC',
							62 => 'NA',
							63 => 'GR',
							64 => 'SO',
							65 => 'AE',
							66 => 'KH',
							67 => 'FI',
							68 => 'WALES',
							69 => 'LC',
							70 => 'SCOTLAND',
							71 => 'RS',
							72 => 'VA',
							73 => 'BR',
							74 => 'AL',
							75 => 'BN',
							76 => 'UM',
							77 => 'LV',
							78 => 'EE',
							79 => 'AW',
							80 => 'KZ',
							81 => 'BI',
							82 => 'BG',
							83 => 'FR',
							84 => 'HM',
							85 => 'RO',
							86 => 'GS',
							87 => 'CA',
							88 => 'SN',
							89 => 'IL',
							90 => 'DM',
							91 => 'SI',
							92 => 'MY',
							93 => 'DJ',
							94 => 'PW',
							95 => 'NG',
							96 => 'GT',
							97 => 'CF',
							98 => 'SG',
							99 => 'IE',
							100 => 'MW',
							101 => 'PY',
							102 => 'TK',
							103 => 'NI',
							104 => 'CH',
							105 => 'TL',
							106 => 'CO',
							107 => 'MP',
							108 => 'MK',
							109 => 'PE',
							110 => 'TW',
							111 => 'GF',
							112 => 'NU',
							113 => 'GA',
							114 => 'NR',
							115 => 'CS',
							116 => 'ML',
							117 => 'PL',
							118 => 'SR',
							119 => 'ZA',
							120 => 'ME',
							121 => 'PK',
							122 => 'GH',
							123 => 'CZ',
							124 => 'SJ',
							125 => 'MZ',
							126 => 'PT',
							127 => 'TF',
							128 => 'GW',
							129 => 'PS',
							130 => 'GP',
							131 => 'NC',
							132 => 'SM',
							133 => 'IO',
							134 => 'TO',
							135 => 'CL',
							136 => 'SC',
							137 => 'MS',
							138 => 'SD',
							139 => 'ZW',
							140 => 'MT',
							141 => 'TH',
							142 => 'GY',
							143 => 'CK',
							144 => 'FAM',
							145 => 'PA',
							146 => 'GB',
							147 => 'MO',
							148 => 'MH',
							149 => 'PF',
							150 => 'TT',
							151 => 'GE',
							152 => 'SV',
							153 => 'IT',
							154 => 'PH',
							155 => 'TZ',
							156 => 'CY',
							157 => 'GL',
							158 => 'JM',
							159 => 'IS',
							160 => 'MA',
							161 => 'FM',
							162 => 'ES',
							163 => 'HR',
							164 => 'ET',
							165 => 'HU',
							166 => 'AF',
							167 => 'RW',
							168 => 'VE',
							169 => 'FJ',
							170 => 'LI',
							171 => 'KE',
							172 => 'BV',
							173 => 'AO',
							174 => 'LU',
							175 => 'AT',
							176 => 'RE',
							177 => 'BJ',
							178 => 'KY',
							179 => 'CATALONIA',
							180 => 'BM',
							181 => 'LR',
							182 => 'AS',
							183 => 'KP',
							184 => 'HN',
							185 => 'EH',
							186 => 'AZ',
							187 => 'BD',
							188 => 'KW',
							189 => 'UG',
							190 => 'PN',
							191 => 'GM',
							192 => 'IR',
							193 => 'MG',
							194 => 'CX',
							195 => 'SY',
							196 => 'ENGLAND',
							197 => 'DZ',
							198 => 'YT',
							199 => 'PG',
							200 => 'GD',
							201 => 'CV',
							202 => 'TR',
							203 => 'NP',
							204 => 'ZM',
							205 => 'MN',
							206 => 'SE',
							207 => 'MU',
							208 => 'TN',
							209 => 'NL',
							210 => 'CM',
							211 => 'SB',
							212 => 'MR',
							213 => 'PR',
							214 => 'GQ',
							215 => 'CC',
							216 => 'JP',
							217 => 'SL',
							218 => 'IN',
							219 => 'DO',
							220 => 'SK',
							221 => 'TG',
							222 => 'NE',
							223 => 'CD',
							224 => 'BE',
							225 => 'BB',
							226 => 'UA',
							227 => 'OM',
							228 => 'LS',
							229 => 'AR',
							230 => 'EG',
							231 => 'LT',
							232 => 'AU',
							233 => 'US',
							234 => 'QA',
							235 => 'AN',
							236 => 'AI',
							237 => 'BW',
							238 => 'HT',
							239 => 'AG',
							240 => 'BY',
							241 => 'FK',
							242 => 'UZ',
							243 => 'KM',
							244 => 'LA',
							245 => 'ER',
							246 => 'VC'
						);
	
	public static function getFlags(array $aGet, Lang $oLang) {
		if (empty($aGet['page']) && empty($aGet['sPage'])) {
			throw new CoreException('missing requested page');
		}
		$sTplName = ADMIN ? 'flag.admin.tpl' : 'flag.tpl';
		$sTpl = file_get_contents(CORE_TPL_PATH.$sTplName);
		$sHtml = '';
		$sPage = isset($aGet['page']) ? $aGet['page'] : $aGet['sPage'];
		// Gestion des sous catégories
		if(strpos($sPage, '_')) {
			$sPage = str_replace('_', '/', $sPage);
		}
		foreach ($oLang->getAvailable() as $sLang) {
			if (in_array($sLang, self::$aFlagsName)) {
				$sHtml .= str_replace(
							array(
								'{__PAGE__}',
								'{__LANG__}',
								'{__ACTIVE__}',
								'{__LANG_LOWER__}'
							), 
							array(
								$sPage,
								$sLang,
								SessionLang::getLang() === $sLang ? ' on' : ' off',
								strtolower($sLang)
							), 
							$sTpl
						);
			}
		}
		return Minifier::minifyHtml($sHtml);
	}
}